# Generated by Django 3.0.2 on 2020-01-27 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='productitems',
        ),
    ]
