# Generated by Django 3.0.2 on 2020-01-29 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogtitle', models.CharField(max_length=200)),
                ('blogbody', models.TextField(max_length=1500)),
                ('img', models.ImageField(upload_to='imgblog')),
                ('postdate', models.DateTimeField(auto_now_add=True, verbose_name='Date (mm/dd/yyyy)')),
                ('blogwriter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog Section',
                'verbose_name_plural': 'Blog Section',
            },
        ),
        migrations.CreateModel(
            name='blogcomment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250)),
                ('comment', models.TextField(max_length=1500)),
                ('commentdate', models.DateTimeField(auto_now_add=True, verbose_name='Date (mm/dd/yyyy)')),
                ('blogpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.blog')),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
