# Generated by Django 3.0.2 on 2020-01-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='blogpost',
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='blogpostid',
            field=models.IntegerField(default=1),
        ),
    ]
