# Generated by Django 3.0.2 on 2020-01-28 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_productitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='accountcart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productitems')),
            ],
        ),
    ]
