# Generated by Django 3.0.2 on 2020-01-28 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountcart_cartowner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='accountcart',
        ),
    ]
