# Generated by Django 3.0.2 on 2020-01-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_cart_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='productcart',
            field=models.CharField(default='', max_length=200),
        ),
    ]
