# Generated by Django 3.0.2 on 2020-01-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200128_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='subtotal',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
