# Generated by Django 3.0.2 on 2020-01-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_cartitem_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='subtotal',
            field=models.FloatField(blank=True, default=models.FloatField(blank=True)),
        ),
    ]
