# Generated by Django 3.0.2 on 2020-01-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='total',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
