# Generated by Django 3.0.2 on 2020-01-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_checkout_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='message',
            field=models.TextField(blank=True, max_length=1500),
        ),
    ]
