# Generated by Django 3.0.2 on 2020-01-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200129_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='orderinfo',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
