# Generated by Django 3.0.2 on 2020-01-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_checkout_orderinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='orderinfo',
            field=models.TextField(blank=True, default={}, max_length=1000),
        ),
    ]
