# Generated by Django 3.0.2 on 2020-01-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20200129_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='orderinfo',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
