# Generated by Django 3.0.2 on 2020-01-29 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productitems'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0017_auto_20200129_0554'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishitems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productwish', models.CharField(default='', max_length=200)),
                ('wishprice', models.FloatField(blank=True)),
                ('cartuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('productcheck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productitems')),
            ],
            options={
                'verbose_name': 'Wish List',
                'verbose_name_plural': 'Wish List',
            },
        ),
    ]
