# Generated by Django 3.0.2 on 2020-01-29 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_wishitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishitems',
            name='productcheck',
        ),
    ]
