# Generated by Django 3.0.2 on 2020-01-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20200129_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishitems',
            name='id',
        ),
        migrations.AddField(
            model_name='wishitems',
            name='wishid',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
