# Generated by Django 3.0.2 on 2020-01-30 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20200129_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishitems',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wishitems',
            name='wishid',
            field=models.IntegerField(default=0),
        ),
    ]
